### ISSUE TITLE
AWS Alexa App Setup

### ISSUE THREAD

**Issue by rustygeldmacher** [alirawashdeh/wunderlist-alexa#2]
Hi there -- I have the skill running on a server, and I have a Wunderlist app set up through their developer portal, but I'm not sure how to configure this skill using the AWS developer portal. Any chance you could guide me through what to put in each field on the app registration screens on Amazon? I'm particularly stuck on the account linking part. Any help you could provide would be amazing. Really looking forward to using this skill!

Thanks,
rg

**Comment by alirawashdeh** [comment]
Hi, 

Some useful settings in the Account Linking section:

Authorization URL: https://www.wunderlist.com/oauth/authorize
Client Secret: [Insert the Client ID from your app on developer.wunderlist.com]
Authorization Grant Type: Auth Code Grant
Access Token URI: https://www.wunderlist.com/oauth/access_token
Client Secret: [Insert the Client secret from your app on developer.wunderlist.com]

That should be it. Make sure you copy one of the Redirect URLs in the Account Linking section  and paste it into the Callback URL for your app on developer.wunderlist.com.

Hope that helps,
Ali

**Comment by rustygeldmacher** [comment]
Hi @alirawashdeh -- thanks so much for the pointers! I have the app set up and  my account linked now. One thing to mention here, in the app setup on the AWS Alexa portal, after you enter the client secret, there's a dropdown for "Client Authentication Scheme". You need to select "Credentials in Request Body" in order to account linking to properly work. Can't wait to start playing around with this. Thanks again!
